spring:
  datasource:
    url: "jdbc:mysql://kkanzo-mysql-music.clavmazlriuu.ap-northeast-2.rds.amazonaws.com/music"
    driver-class-name: com.mysql.jdbc.Driver
    username: kkanzo
    password: qwer1234
  jpa:
    database: mysql
    generate-ddl: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL55Dialect
  session:
    store-type: redis
    redis:
      flush-mode: on-save
      namespace: 'spring:session'
  redis:
    host: 10.10.16.244
    port: 6379
server:
  servlet:
    session:
      timeout: 3000
      
management:
  endpoints:
    web:
      exposure:
        include: "*"